#!/usr/bin/env python3
"""File Phase 1-3 feature issues on GitHub."""
import json, os, urllib.request, urllib.error

TOKEN = os.environ["GH_TOKEN"]
REPO = "Roy-Wanyoike/Aurevia"

ISSUES = [
    # ─── PHASE 1: MARKET FOUNDATION ──────────────────────────────────────────
    {"title": "[PHASE1] Watchlists — save and track custom asset lists", "body": "## Problem\nNo watchlist feature. Users can't save custom lists of assets to track.\n\n## Spec (from brief)\nWatchlists should surface: real-time prices, change%, mini-sparkline, quick-add/remove, drag-to-reorder, multiple named lists.\n\n## Fix\n1. `Watchlist` model in Prisma (name, symbols[], userId, organizationId)\n2. `/api/v1/watchlists` CRUD routes\n3. `useWatchlists` hook\n4. New `Watchlists` view in sidebar (under Market Intelligence)\n5. Add 'Add to watchlist' button on Asset Detail page\n6. Star icon on Markets table rows to add/remove\n\n## Acceptance\n- Create named watchlists\n- Add/remove assets\n- View real-time prices for watchlist assets\n- Multiple watchlists supported", "labels": ["phase1", "feature", "market-data"]},
    {"title": "[PHASE1] Smart Screener — multi-factor asset filtering", "body": "## Problem\nMarkets view has a basic search filter. No real screener with multi-factor queries.\n\n## Spec (from brief)\nScreener supports: price, market cap, volume, RSI, MACD, EMA, volatility, momentum, trend, regime, sector, P/E, earnings growth, debt. Eventually natural-language.\n\n## Fix\n1. New `Screener` view with filter builder UI\n2. Filters: assetType, sector, priceRange, volumeMin, rsiRange, trendDirection, regime, volatilityMax, changePctMin\n3. Results table (reuse Markets table component)\n4. Save/load screen configurations\n5. `/api/v1/screener` POST route with filter JSON\n6. Command palette: 'run screener'\n\n## Acceptance\n- Filter by: sector=Technology AND rsi<40 AND trend=UP\n- Results update in real-time\n- Save screen presets", "labels": ["phase1", "feature", "intelligence"]},
    {"title": "[PHASE1] Market Pulse — global market health dashboard", "body": "## Problem\nNo global market health overview. Dashboard shows portfolio + signals but not market-wide breadth.\n\n## Spec (from brief)\nMarket Pulse: advancers/decliners, regime distribution, sector rotation, fear/greed sentiment, market breadth.\n\n## Fix\n1. New `MarketPulse` view (first under Market Intelligence)\n2. Cards: Advancers vs Decliners (bar), Regime Distribution (donut), Sector Performance (heatmap), Breadth (new highs vs new lows)\n3. Fear/Greed-style composite score (0-100)\n4. Market breadth: % assets above SMA50, % above SMA200\n5. `/api/v1/market-pulse` route computing these aggregations\n\n## Acceptance\n- See market-wide health at a glance\n- Advancers/decliners ratio\n- Sector rotation visible\n- Breadth indicators", "labels": ["phase1", "feature", "intelligence"]},
    {"title": "[PHASE1] Correlation matrix — cross-asset relationships", "body": "## Problem\nNo correlation analysis. Users can't see how assets move together.\n\n## Fix\n1. Compute correlation matrix across all 18 assets using 30-day returns\n2. `/api/v1/correlation` route returning matrix\n3. Correlation heatmap view (color-coded: green=positive, red=negative)\n4. Click any cell → show scatter plot of the two assets' returns\n\n## Acceptance\n- 18×18 correlation matrix rendered as heatmap\n- Hover shows exact correlation coefficient\n- Click opens scatter plot", "labels": ["phase1", "feature", "analytics"]},
    # ─── PHASE 2: INTELLIGENCE ───────────────────────────────────────────────
    {"title": "[PHASE2] Historical Memory — similarity search engine", "body": "## Problem\nNo historical similarity search. Can't find 'similar historical setups' to current market conditions.\n\n## Spec (from brief)\nFor current market state (RSI, EMA, volume, ATR, regime), search historical periods with similar characteristics. Return: similarity score, sample count, forward returns (1d/1w/1m), win rate.\n\n## Fix\n1. Store historical market states in `HistoricalPattern` table (already in schema)\n2. `src/lib/aurevia/intelligence/similarity.ts` — compute similarity score (cosine or Euclidean distance on normalized features)\n3. `/api/v1/similarity/[symbol]` route — finds top N similar historical periods\n4. New `HistoricalMemory` view showing: current state, top 10 matches, forward return distribution, win rate\n5. CRITICAL: label as 'evidence, not prediction'\n\n## Acceptance\n- For AAPL, find 10 most similar historical setups\n- Show forward 5-day and 20-day returns for each match\n- Display median/mean/max/min forward returns\n- Clear disclaimer: 'Historical evidence, not prediction'", "labels": ["phase2", "feature", "intelligence"]},
    {"title": "[PHASE2] News Intelligence — entity extraction + sentiment", "body": "## Problem\nNo news feature. `NewsArticle` table exists in schema but is empty.\n\n## Fix\n1. `src/lib/aurevia/intelligence/news.ts` — news aggregation service\n2. Integrate Finnhub news API (key already in .env.example)\n3. Extract mentioned symbols from headlines\n4. Compute sentiment (-1 to +1) using simple keyword scoring\n5. `/api/v1/news` route — list news, filter by symbol\n6. New `News` view in sidebar\n7. Show news on Asset Detail page (recent articles for that symbol)\n8. News-to-price correlation: 'This type of news historically produced +1.5% moves'\n\n## Acceptance\n- News view shows recent market news with sentiment\n- Asset detail shows symbol-specific news\n- Without API key, show empty state (not fabricated)", "labels": ["phase2", "feature", "intelligence"]},
    {"title": "[PHASE2] Market Events — earnings, economic calendar", "body": "## Problem\nNo event calendar. `MarketEvent` table exists but is empty.\n\n## Fix\n1. `src/lib/aurevia/intelligence/events.ts` — event tracking service\n2. Integrate Finnhub earnings calendar API\n3. Store events in `MarketEvent` table\n4. `/api/v1/events` route — list upcoming events, filter by type/symbol/date\n5. New `Events` view showing calendar\n6. Event risk scoring: HIGH/MEDIUM/LOW based on historical volatility\n7. Show on Asset Detail page if earnings approaching\n\n## Acceptance\n- Events view shows upcoming earnings, economic releases\n- Filter by symbol, type, date range\n- Event risk level displayed", "labels": ["phase2", "feature", "intelligence"]},
    {"title": "[PHASE2] Alert Engine — price, indicator, risk alerts", "body": "## Problem\nNo alert system. `Alert` table exists but no UI or engine.\n\n## Spec (from brief)\nAlerts for: price crosses threshold, RSI < 30, volume spike, regime change, drawdown limit, broker disconnect, stale data.\n\n## Fix\n1. `src/lib/aurevia/alerts/engine.ts` — alert evaluation on every tick\n2. `/api/v1/alerts` CRUD routes\n3. `useAlerts` hook\n4. New `Alerts` view — create/manage alerts, view triggered alerts\n5. Alert creation modal: select type → symbol → condition → threshold → channel (in-app/email/webhook)\n6. In-app notification (sonner toast) when alert triggers\n7. System alerts (broker disconnect, stale data) auto-created\n\n## Acceptance\n- Create alert: 'AAPL RSI < 30'\n- When RSI drops below 30, toast fires\n- Alerts view shows all alerts + triggered history", "labels": ["phase2", "feature", "automation"]},
    {"title": "[PHASE2] Opportunity Radar — continuous opportunity scanning", "body": "## Problem\nNo opportunity discovery. Users must manually browse markets.\n\n## Spec (from brief)\nRadar scans for: breakouts, momentum, mean reversion, trend continuation, reversals, volume anomalies, volatility opportunities. Ranks by conviction, risk, liquidity, historical evidence, strategy agreement.\n\n## Fix\n1. `src/lib/aurevia/intelligence/radar.ts` — scans universe every 30s\n2. Categorize: Breakout (N), Momentum (N), Mean Reversion (N), Risk Events (N)\n3. `/api/v1/radar` route returning categorized opportunities\n4. New `OpportunityRadar` view — grid of cards by category\n5. Each card: symbol, signal, conviction score, risk score, historical evidence\n6. Click → opens Asset Detail\n7. Command palette: 'view opportunity radar'\n\n## Acceptance\n- Radar view shows live opportunities by category\n- Each opportunity has conviction + risk score\n- Updates every 30s", "labels": ["phase2", "feature", "intelligence"]},
    # ─── PHASE 3: RESEARCH ───────────────────────────────────────────────────
    {"title": "[PHASE3] Market Replay — replay historical markets bar-by-bar", "body": "## Problem\nNo market replay. Can't practice trading against historical data without knowing the future.\n\n## Spec (from brief)\nPick date, asset, timeframe. Replay market bar-by-bar. User can trade without knowing the future. For strategy development, training, QA.\n\n## Fix\n1. `src/lib/aurevia/replay/engine.ts` — replay state machine\n2. `/api/v1/replay/start` POST — start replay session (symbol, date, timeframe, capital)\n3. `/api/v1/replay/next` POST — advance N bars\n4. `/api/v1/replay/trade` POST — place order at current bar\n5. New `MarketReplay` view — chart shows bars up to 'cursor', hidden future\n6. Controls: Play/Pause, Step Forward, Speed (1x/2x/5x)\n7. Trade ticket to place orders at current bar\n8. P&L tracked in real-time\n\n## Acceptance\n- Select AAPL, Jan 2024, 1d\n- See candles up to Jan 15\n- Click 'Next' → Jan 16 appears\n- Place BUY order → tracked\n- Future bars hidden until advanced", "labels": ["phase3", "feature", "research"]},
    {"title": "[PHASE3] What-If Simulator — scenario analysis", "body": "## Problem\nNo scenario analysis. Can't ask 'what if NVDA falls 15%'?\n\n## Spec (from brief)\nWhat-if: NVDA falls 15%, rates increase, BTC drops 30%, tech sector falls 10%. Calculate estimated portfolio impact.\n\n## Fix\n1. `src/lib/aurevia/simulation/scenario.ts` — scenario engine\n2. `/api/v1/scenario` POST — run scenario\n3. New `WhatIfSimulator` view\n4. Preset scenarios: market crash, sector rotation, rate hike, crypto crash\n5. Custom scenario builder: select shock (e.g., 'NVDA -15%') → apply to portfolio → see impact\n6. Show: current equity vs scenario equity, P&L impact, positions affected\n7. Correlation-aware (if tech falls, related assets move too)\n\n## Acceptance\n- 'What if NVDA falls 15%' → shows portfolio impact\n- Affected positions highlighted\n- Correlated assets also impacted", "labels": ["phase3", "feature", "simulation"]},
    {"title": "[PHASE3] Portfolio Analytics — VaR, CVaR, beta, factor exposure", "body": "## Problem\nPortfolio view shows basic positions/P&L but no risk analytics.\n\n## Spec (from brief)\nPortfolio intelligence: risk score, concentration, sector exposure, correlation risk, beta, factor exposure, VaR, CVaR, stress testing.\n\n## Fix\n1. `src/lib/aurevia/portfolio/analytics.ts` — compute:\n   - VaR (95%, 99%) — historical method\n   - CVaR (expected shortfall)\n   - Beta vs SPY\n   - Sector exposure breakdown\n   - Concentration index (Herfindahl)\n   - Correlation-adjusted exposure\n2. `/api/v1/portfolio/analytics` route\n3. New `PortfolioAnalytics` section in Portfolio view\n4. Cards: VaR, CVaR, Beta, Concentration, Sector breakdown donut\n\n## Acceptance\n- VaR(95%): '95% confidence max 1-day loss = $X'\n- Sector breakdown: '68% Technology, 15% Financials...'\n- Beta vs SPY shown", "labels": ["phase3", "feature", "analytics"]},
    {"title": "[PHASE3] Risk Cockpit — real-time risk monitoring center", "body": "## Problem\nRisk view exists but is basic. Need a mission-control-style risk center.\n\n## Spec (from brief)\nRisk Cockpit: portfolio exposure, leverage, open risk, daily loss, drawdown, VaR, liquidity, volatility, broker health, execution risk, concentration, circuit-breaker state — all in one view.\n\n## Fix\n1. Enhance `RiskView` into a full Risk Cockpit\n2. Add: VaR display, liquidity score, execution quality metrics, concentration heatmap\n3. Real-time risk gauge (0-100 risk score)\n4. Historical risk events timeline\n5. Emergency controls: Soft Stop / Hard Stop / Emergency Stop\n6. All limits vs current values with visual indicators\n\n## Acceptance\n- Single view shows all risk metrics\n- Risk score gauge visible\n- Emergency stop buttons (with confirmation)", "labels": ["phase3", "feature", "risk"]},
    {"title": "[PHASE3] Trading Journal — auto-recorded with behavioral analytics", "body": "## Problem\nNo trading journal. Can't review past trades + learn from patterns.\n\n## Spec (from brief)\nAuto-record: trade, entry reason, strategy, signal, risk decision, entry/exit, P&L, regime, market conditions, outcome. AI identifies behavioral patterns ('losing trades 64% after high-volatility regimes').\n\n## Fix\n1. `src/lib/aurevia/journal/engine.ts` — auto-record every trade\n2. `TradingJournal` model in Prisma (already covered by Order + Signal tables)\n3. `/api/v1/journal` route — list trades with context\n4. New `TradingJournal` view\n5. Each trade shows: entry/exit, P&L, regime at entry, strategy, risk decision, signal reasons\n6. Analytics tab: win rate by regime, by strategy, by time-of-day, by volatility\n7. Behavioral insights: 'Your losing trades occur 64% after high-vol regimes'\n\n## Acceptance\n- Every executed trade auto-recorded\n- Journal shows trade + context\n- Analytics reveal behavioral patterns", "labels": ["phase3", "feature", "portfolio"]},
    # ─── PHASE 4: ADVANCED ───────────────────────────────────────────────────
    {"title": "[PHASE4] AI Research Copilot — natural-language research assistant", "body": "## Problem\nNo AI copilot. Can't ask 'Why is NVDA moving today?' or 'Find stocks with strong momentum + low volatility'.\n\n## Spec (from brief)\nAI copilot answers research questions with evidence + calculations, not invented explanations. Examples: 'Why is NVIDIA moving?', 'Find historical periods similar to this', 'Which stocks have strong momentum but low volatility?', 'Explain why this signal was generated', 'Compare this strategy against SPY over 5 years'.\n\n## Fix\n1. `src/lib/aurevia/ai/copilot.ts` — Z.ai SDK integration\n2. Context-aware: copilot can call /api/v1/* routes to fetch real data\n3. System prompt: 'You are Aurevia's research copilot. Answer with evidence + data. Never fabricate. If you don't know, say so.'\n4. New `AICopilot` view — chat interface\n5. Suggested questions shown as chips\n6. Responses include: data tables, chart references, links to relevant views\n7. Command palette: 'ask copilot'\n\n## Acceptance\n- Ask 'Why is AAPL moving?' → shows recent news + signals + indicators\n- Ask 'Find low-volatility momentum stocks' → returns filtered results\n- No fabricated data — pulls from real API", "labels": ["phase4", "feature", "ai"]},
    {"title": "[PHASE4] Strategy Builder — visual no-code strategy editor", "body": "## Problem\nStrategies are code-only. Non-technical users can't create strategies.\n\n## Spec (from brief)\nVisual builder: WHEN RSI < 30 AND EMA20 > EMA50 AND Volume > 1.5×Avg THEN BUY. Risk: position=2%, stop=2%, target=6%. No coding required.\n\n## Fix\n1. `src/lib/aurevia/strategies/builder.ts` — strategy genome representation\n2. New `StrategyBuilder` view\n3. Block-based UI: Entry conditions (AND/OR), Exit conditions, Risk rules, Regime filter\n4. Each block is a dropdown: indicator → operator → value\n5. Preview: 'This strategy would have generated N signals in last 30 days'\n6. Backtest button → runs backtest with the custom strategy\n7. Save strategy → added to Strategies list\n\n## Acceptance\n- Build: WHEN RSI<30 AND EMA20>EMA50 THEN BUY\n- Preview shows historical signals\n- Backtest runs against it\n- Save to strategy list", "labels": ["phase4", "feature", "research"]},
    {"title": "[PHASE4] Monte Carlo + Walk-Forward validation", "body": "## Problem\nBacktests run once. No Monte Carlo or walk-forward robustness testing.\n\n## Spec (from brief)\nMonte Carlo: simulate trade sequence variations, slippage variations, return distributions, drawdown distributions, risk of ruin. Walk-forward: Train→Test→Train→Test across rolling windows.\n\n## Fix\n1. `src/lib/aurevia/backtest/monte-carlo.ts` — run N simulations with perturbed parameters\n2. `src/lib/aurevia/backtest/walk-forward.ts` — rolling window validation\n3. Enhance Backtests view with 'Robustness' tab\n4. Robustness score: Backtest × Walk-forward × Monte Carlo × Regime-tested × Slippage × Out-of-sample\n5. Charts: return distribution, drawdown distribution, equity percentiles\n6. `/api/v1/backtests/[id]/monte-carlo` route\n\n## Acceptance\n- Run 1000 Monte Carlo simulations on a backtest\n- See percentile equity bands (10th/50th/90th)\n- Walk-forward shows stability across windows\n- Robustness score calculated", "labels": ["phase4", "feature", "research"]},
]

def create_issue(issue):
    data = json.dumps(issue).encode()
    req = urllib.request.Request(
        f"https://api.github.com/repos/{REPO}/issues",
        data=data,
        headers={"Authorization": f"token {TOKEN}", "Accept": "application/vnd.github+json", "Content-Type": "application/json"},
        method="POST",
    )
    try:
        with urllib.request.urlopen(req) as resp:
            return json.loads(resp.read()).get("number")
    except urllib.error.HTTPError as e:
        print(f"ERROR: {e.read().decode()[:200]}")
        return None

if __name__ == "__main__":
    for label in ["phase1", "phase2", "phase3", "phase4", "feature", "market-data", "intelligence", "analytics", "automation", "risk", "portfolio", "research", "simulation", "ai"]:
        req = urllib.request.Request(
            f"https://api.github.com/repos/{REPO}/labels",
            data=json.dumps({"name": label, "color": "0e8a16" if "phase" in label else "ededed"}).encode(),
            headers={"Authorization": f"token {TOKEN}", "Accept": "application/vnd.github+json", "Content-Type": "application/json"},
            method="POST",
        )
        try: urllib.request.urlopen(req)
        except urllib.error.HTTPError: pass
    created = []
    for issue in ISSUES:
        num = create_issue(issue)
        if num:
            created.append(num)
            print(f"#{num}: {issue['title'][:70]}")
    print(f"\nCreated {len(created)} Phase 1-4 issues")
