#!/usr/bin/env python3
"""File Phase 0 production-foundation issues on GitHub."""
import json, os, urllib.request, urllib.error

TOKEN = os.environ["GH_TOKEN"]
REPO = "Roy-Wanyoike/Aurevia"

ISSUES = [
    {"title": "[PHASE0][SECURITY] Remove hardcoded symbol lists — fetch from /api/v1/markets everywhere", "body": "## Problem\nThe chat history repeatedly says 'Connect with APIs don't hardcode.' Several views still hardcode symbol lists or strategy keys instead of fetching them dynamically.\n\n## Audit\nRun: `grep -rn 'const SYMBOLS' src/components/aurevia/views/` and `grep -rn 'const STRATEGY' src/components/`.\n\n## Fix\n- Every dropdown should fetch from the appropriate API\n- No hardcoded arrays of symbols, strategies, timeframes, or regimes\n- All data comes from API routes\n\n## Acceptance\n- `grep -rn 'const SYMBOLS' src/components/` returns 0 hits\n- All dropdowns are data-driven", "labels": ["phase0", "security", "data-quality"]},
    {"title": "[PHASE0][SECURITY] Remove all hardcoded colors — use CSS variables + semantic helpers", "body": "## Problem\n62 direct `text-emerald-400`/`text-red-400` usages across 15 files bypass the semantic color helpers in format.ts. This violates the design system — emerald should only be used for gains/approvals.\n\n## Fix\n- Replace direct color classes with semantic helpers: `gainColor()`, `gainBg()`, `actionColor()`, `regimeColor()`, `breakerColor()`, `decisionColor()`, `trendColor()`, `drawdownColor()`\n- For non-semantic uses, use Tailwind variables: `text-primary`, `text-muted-foreground`, `text-destructive`\n\n## Acceptance\n- `grep -rn 'text-emerald-400' src/components/aurevia/views/ | wc -l` < 5 (only in semantic helper definitions)", "labels": ["phase0", "design-system", "ui/ux"]},
    {"title": "[PHASE0][TESTING] Set up vitest + write 100+ unit tests for financial calculations", "body": "## Problem\nZero test coverage. Every financial calculation needs unit tests with known expected values.\n\n## Fix\n1. Install vitest: `bun add -d vitest @vitejs/plugin-react`\n2. Create `vitest.config.ts`\n3. Write tests for:\n   - **Indicators** (SMA, EMA, RSI, MACD, Bollinger, ATR, ADX, Stochastic, VWAP, OBV, ROC) — verify against known input/output pairs\n   - **Risk engine** — each of the 11 rules + circuit breaker state machine transitions\n   - **Portfolio accounting** — long, short, flips, P&L, drawdown, exposure\n   - **Backtest metrics** — Sharpe, Sortino, Calmar, max DD, win rate, profit factor\n   - **Paper broker** — fill matching, commission, slippage, reconciliation\n   - **Strategy evaluation** — each strategy's BUY/SELL/HOLD logic\n   - **ML models** — predict() output ranges, no NaN\n4. Add `bun test` to CI\n5. Target > 80% coverage on `src/lib/aurevia/**`\n\n## Acceptance\n- `bun test` runs and passes\n- 100+ test cases\n- Coverage > 80% on lib/aurevia/", "labels": ["phase0", "testing", "quality"]},
    {"title": "[PHASE0][CI/CD] Create GitHub Actions CI pipeline", "body": "## Problem\nNo CI/CD pipeline. Pushes aren't validated.\n\n## Fix\nCreate `.github/workflows/ci.yml`:\n```yaml\nname: CI\non: [push, pull_request]\njobs:\n  quality:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - uses: oven-sh/setup-bun@v1\n      - run: bun install\n      - run: bun run lint\n      - run: npx tsc --noEmit\n      - run: bun test  # once tests exist\n      - run: bun run db:push  # verify schema\n```\n\nAlso add:\n- `.github/workflows/deploy.yml` (manual trigger for production)\n- PR template requiring issue reference\n- Branch protection rules (require CI pass, require PR review)\n\n## Acceptance\n- PR to main triggers CI\n- CI must pass before merge\n- PR template closes issue on merge", "labels": ["phase0", "ci-cd", "devops"]},
    {"title": "[PHASE0][OBSERVABILITY] Add structured logging + request IDs + correlation IDs", "body": "## Problem\nNo structured logging. API errors are logged as plain strings. No request IDs to trace a trade through the pipeline.\n\n## Fix\n1. Create `src/lib/aurevia/logger.ts` — structured logger (pino or winston)\n2. Middleware to attach `x-request-id` header to every request\n3. Every API route logs: `{requestId, method, path, status, durationMs}`\n4. Every risk evaluation logs: `{requestId, signalId, decision, reasons}`\n5. Every order logs: `{requestId, orderId, symbol, side, qty, status}`\n6. Frontend sends `x-request-id` on every fetch (generated client-side)\n\n## Acceptance\n- Every API response has `x-request-id` header\n- Logs are JSON-parseable\n- A trade can be traced end-to-end via correlation ID", "labels": ["phase0", "observability", "backend"]},
    {"title": "[PHASE0][SECURITY] API rate limiting middleware", "body": "## Problem\nNo rate limiting. The API is vulnerable to abuse.\n\n## Fix\n1. Add rate-limiting middleware using `@upstash/ratelimit` or a simple in-memory counter\n2. Default: 60 requests/minute per IP\n3. Higher limits for authenticated users\n4. Return 429 with `Retry-After` header when exceeded\n5. Apply to all `/api/v1/*` routes\n\n## Acceptance\n- 61st request in a minute returns 429\n- `Retry-After` header present", "labels": ["phase0", "security", "backend"]},
    {"title": "[PHASE0][DATA] Integrate real market data provider (Polygon.io)", "body": "## Problem\nAll market data is simulated. The brief says 'Do not use fake market data in production.'\n\n## Fix\n1. Create `src/lib/aurevia/market-data/providers/polygon.ts` implementing the `MarketDataProvider` interface\n2. Fetch real candles: `GET https://api.polygon.io/v2/aggs/ticker/{symbol}/range/1/day/{from}/{to}`\n3. Fetch real quotes: `GET https://api.polygon.io/v2/last/trade/{symbol}`\n4. Cache results to avoid rate limits\n5. Fall back to simulated feed if API key is missing (clearly labeled)\n6. Show data source badge in UI: 'Live (Polygon)' vs 'Simulated'\n\n## Acceptance\n- With `POLYGON_API_KEY` set, dashboard shows real AAPL prices\n- Without key, falls back to simulated + shows 'Simulated' badge\n- Source is visible in the UI", "labels": ["phase0", "market-data", "backend"]},
    {"title": "[PHASE0][UX] Humanized UI — not AI-generated looking", "body": "## Problem\nThe UI looks 'AI-generated' — too uniform, too perfect, lacks the character of a real fintech product built by humans. The PM/UX/HCD team should research what makes UIs feel human.\n\n## Research Findings (PM + UX + HCD team):\nReal fintech terminals have:\n- **Information density** — not lots of whitespace; data is king\n- **Personality** — Bloomberg has its orange-on-black; TradingView has playful gradients\n- **Texture** — subtle noise, not flat solid colors\n- **Micro-interactions** — subtle hovers, not none\n- **Real numbers** — not rounded placeholders\n- **Density modes** — compact / comfortable / spacious\n- **Keyboard-first** — power users hate mice\n- **Contextual** — right info at right time, not everything everywhere\n\n## Fix\n1. Add subtle background texture (very low opacity noise SVG)\n2. Add a density toggle (compact/comfortable) in settings\n3. Add keyboard shortcut hints in nav (⌘K, ⌘B, etc.)\n4. Make stat tiles show real deltas, not placeholder 0s\n5. Add 'last updated' timestamps on every data card\n6. Add a subtle border-glow on the active nav item\n7. Add number formatting that respects locale (1,234.56 vs 1.234,56)\n8. Make loading skeletons shimmer, not just pulse\n\n## Acceptance\n- UI feels like a real product, not a demo\n- Designers would not immediately say 'this looks AI-generated'", "labels": ["phase0", "ui/ux", "hcd", "design"]},
    {"title": "[PHASE0][UX] Command palette (Cmd+K) — navigate, search, act", "body": "## Problem\nNo Cmd+K command palette. Power users expect this in a trading terminal.\n\n## Fix\n1. Use `cmdk` (already installed) + shadcn `Command` component\n2. Commands:\n   - Navigate to any view (Dashboard, Markets, Signals, etc.)\n   - Search assets (type 'AAPL' → opens asset detail)\n   - Run actions (Scan signals, Run backtest, Reset portfolio)\n   - Toggle settings (density mode, theme info)\n3. Global keyboard shortcut: Cmd+K / Ctrl+K\n4. Recent commands shown first\n5. Fuzzy search\n\n## Acceptance\n- Cmd+K opens palette\n- Type 'aap' → shows AAPL\n- Enter navigates to asset\n- Escape closes", "labels": ["phase0", "ui/ux", "power-user"]},
    {"title": "[PHASE0][UX] URL routing — view state in URL, not just Zustand", "body": "## Problem\nView state lives only in Zustand. Refresh returns to Dashboard. Back button doesn't work. Can't share URLs.\n\n## Fix\n1. Sync Zustand view state with URL query params: `?view=markets&symbol=AAPL`\n2. On mount, read URL params → set Zustand state\n3. On view/symbol change, update URL (pushState)\n4. Back/forward buttons work (popstate listener)\n5. Backtest results shareable: `?view=backtests&id=bt-123`\n\n## Acceptance\n- Refresh on `/markets` stays on Markets\n- Back button works\n- Shareable URLs", "labels": ["phase0", "ui/ux", "architecture"]},
    {"title": "[PHASE0][DOCS] Investor-ready README", "body": "## Problem\nCurrent README is engineering-focused. Need a version that attracts recruiters and investors.\n\n## Fix\nRewrite README.md with:\n1. **Hero section** — one-line value prop + logo + live demo link\n2. **Why Aurevia?** — 3 bullet points on differentiation\n3. **Architecture diagram** — visual, not ASCII\n4. **Feature showcase** — screenshots of the polished UI\n5. **Tech stack** — clean table\n6. **Quick start** — 3 commands\n7. **Roadmap** — phases 0-10, visually appealing\n8. **For investors** — market size, business model, traction placeholders\n9. **For engineers** — link to ARCHITECTURE.md + CONTRIBUTING.md\n10. **License + disclaimer**\n\n## Acceptance\n- README renders beautifully on GitHub\n- A recruiter would understand what Aurevia is in 30 seconds\n- An investor would see the vision", "labels": ["phase0", "docs", "investors"]},
    {"title": "[PHASE0][DOCS] CONTRIBUTING.md + LICENSE + issue/PR templates", "body": "## Problem\nNo contributing guide, no license, no issue/PR templates.\n\n## Fix\n1. `CONTRIBUTING.md` — how to set up dev env, branch naming, PR process, code style\n2. `LICENSE` — choose MIT or Apache 2.0\n3. `.github/ISSUE_TEMPLATE/bug_report.md`\n4. `.github/ISSUE_TEMPLATE/feature_request.md`\n5. `.github/PULL_REQUEST_TEMPLATE.md` — requires `Closes #N`\n6. `.github/FUNDING.yml` — sponsor button\n\n## Acceptance\n- New contributor can set up dev env from CONTRIBUTING.md\n- Issue templates appear when creating issues\n- PR template requires issue reference", "labels": ["phase0", "docs", "community"]},
]

def create_issue(issue):
    data = json.dumps(issue).encode()
    req = urllib.request.Request(
        f"https://api.github.com/repos/{REPO}/issues",
        data=data,
        headers={"Authorization": f"token {TOKEN}", "Accept": "application/vnd.github+json", "Content-Type": "application/json"},
        method="POST",
    )
    try:
        with urllib.request.urlopen(req) as resp:
            result = json.loads(resp.read())
            return result.get("number")
    except urllib.error.HTTPError as e:
        print(f"ERROR: {e.read().decode()[:200]}")
        return None

if __name__ == "__main__":
    # Create labels
    for label in ["phase0", "ci-cd", "devops", "data-quality", "market-data", "hcd", "community", "investors", "docs"]:
        req = urllib.request.Request(
            f"https://api.github.com/repos/{REPO}/labels",
            data=json.dumps({"name": label, "color": "fbca04" if label == "phase0" else "ededed"}).encode(),
            headers={"Authorization": f"token {TOKEN}", "Accept": "application/vnd.github+json", "Content-Type": "application/json"},
            method="POST",
        )
        try: urllib.request.urlopen(req)
        except urllib.error.HTTPError: pass
    created = []
    for issue in ISSUES:
        num = create_issue(issue)
        if num:
            created.append(num)
            print(f"#{num}: {issue['title'][:70]}")
    print(f"\nCreated {len(created)} Phase 0 issues")
